### ISSUE TITLE
Nodejs 12.x for custom resources

### ISSUE THREAD

**Issue by estgueva** [aws-samples/amazon-eks-using-cdk-typescript#10]
The custom resources are being created with runtime nodejs 12.x by default causing the deployment to fail

**Comment by espotti-crubyt** [comment]
+1 I have the same issue with custom resources, but when I upgrade aws-cdk-lib I saw the new runtimes enabled in the functions of aws-cdk-lib/lambdanodejs library. But the new error is with Semver:

`amazon-eks-using-cdk-typescript\node_modules\aws-cdk-lib\node_modules\semver\classes\semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
            ^
TypeError: Invalid Version: ${Token[TOKEN.1056]}.0
    at new SemVer (\amazon-eks-using-cdk-typescript\node_modules\aws-cdk-lib\node_modules\semver\classes\semver.js:38:13)
    at new Cluster (\amazon-eks-using-cdk-typescript\node_modules\aws-cdk-lib\aws-eks\lib\cluster.js:1:9382)
    at new Ekstack (\amazon-eks-using-cdk-typescript\lib\eks-cdk-js-stack.ts:105:20)  
    at Object.<anonymous> (\amazon-eks-using-cdk-typescript\bin\eks-cdk-js.ts:18:13)  
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.m._compile (\amazon-eks-using-cdk-typescript\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.require.extensions.<computed> [as .ts] (\amazon-eks-using-cdk-typescript\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)

Subprocess exited with error 1`
